LiveStreamStore.Web.Frontend/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Data.DBContext.Models;
using LiveStreamStore.Lib.Models;
using LiveStreamStore.Lib.Services.Geos;
using LiveStreamStore.Lib.Services.Logs;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class AddressController : BaseController
    {
        private readonly IAddressService _AddressService;
        private readonly ILogService _LogService;

        public AddressController(IAddressService addressService, ILogService logService)
        {
            _AddressService = addressService;
            _LogService = logService;
        }

        [HttpPost]
        public IActionResult CreateOrUpdate(Address address)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (address.Id == 0)
                {
                    error = _AddressService.CreateAddress(address);
                }
                else
                {
                    error = _AddressService.UpdateAddress(address);
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
            finally
            {
                var method = MethodBase.GetCurrentMethod();
                _Log.Info(_LogService.WriteLogFrontend(method, address));
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Data.DBContext.Models;
using LiveStreamStore.Lib.Models;
using LiveStreamStore.Lib.Services.Cart;
using LiveStreamStore.Lib.Services.Customers;
using LiveStreamStore.Lib.Services.Products;
using LiveStreamStore.Lib.Services.WorkContext;
using LiveStreamStore.Web.Frontend.Filters;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class CartController : BaseController
    {
        private readonly IProductService _ProductService;
        private readonly IWorkContext _WorkContext;
        private readonly ICustomerService _CustomerService;
        private readonly ICartService _CartService;

        public CartController(IProductService productService, IWorkContext workContext, ICustomerService customerService, ICartService cartService)
        {
            _ProductService = productService;
            _WorkContext = workContext;
            _CustomerService = customerService;
            _CartService = cartService;
        }

        [AuthFilter]
        public IActionResult Index()
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                ViewBag.StateProvince = GetAllStateProvince();
                string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                if (_Customer != null)
                {
                    ViewBag.CookieCart = _CartService.GetListProductByStoreCode(_Customer.Id, Path[1]);
                    var customer = _CustomerService.GetCustomerById(_Customer.Id);
                    ViewBag.Address = GetAddress(_Customer.Id);
                    return View(customer);
                }
                ViewBag.CookieCart = GetCookieCartByStoreCode();
                return View();
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        [HttpPost]
        public PartialViewResult GetListCart()
        {
            try
            {
                if (_Customer == null)
                {
                    ViewBag.CookieCart = GetCookieCartByStoreCode();
                    List<Product> products = new List<Product>();
                    if (ViewBag.CookieCart != null)
                    {
                        foreach (var item in ViewBag.CookieCart)
                        {
                            if (item.Id != 0)
                            {
                                products.Add(_ProductService.GetProductById(item.Id));
                            }
                        }
                    }
                    return PartialView("_PartialListCart", products);
                }
                else
                {
                    string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                    ViewBag.ListCart = _CartService.GetListProductByStoreCode(_Customer.Id, Path[1]);
                    return PartialView("_PartialListCart");
                }
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public IActionResult GetProductCartById(int IdProduct)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var product = _ProductService.GetProductById(IdProduct);
                product.ProductInfo.Image = null;
                product.ProductInfo.Product = null;
                return Json(product);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        //Lưu sản phẩm khi click vào thêm sản phẩm
        [HttpPost]
        public IActionResult SetCart(int LivestreamId, int ProductId, int Quantity, int Limited)
        {
            var error = new ErrorObject(Error.SUCCESS);
            var check = new ErrorObject(Error.SUCCESS);
            try
            {
                if (_Customer == null)
                {
                    var list = GetCookieCartByStoreCode();
                    if (list.Count != 0)
                    {
                        for (int i = 0; i < list.Count; i++)
                        {
                            if (list[i].Id == ProductId)
                            {
                                check = _ProductService.CheckProduct(ProductId, (list[i].Quantity + Quantity));
                                break;
                            }
                        }
                    }
                    else
                    {
                        check = _ProductService.CheckProduct(ProductId, Quantity);
                    }
                    if (check.Code != error.Code)
                    {
                        return Json(check);
                    }

                    var value = _WorkContext.checkCookieCart(ProductId, Quantity);
                    if (value == true)
                    {
                        string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                        SetCookieCart(ProductId, Quantity, Limited, LivestreamId, Path[1]);
                    }
                    else
                    {
                        return Json(Error.LIMITED);
                    }
                }
                else
                {
                    ShoppingCart shoppingCart = new ShoppingCart();
                    shoppingCart.CustomerId = _Customer.Id;
                    shoppingCart.LivestreamId = LivestreamId;
                    shoppingCart.ProductId = ProductId;
                    shoppingCart.Quantity = Quantity;
                    error = _CartService.CreateCart(shoppingCart);
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        //Lấy để set số sản phảm của giỏ hàng
        [HttpPost]
        public int GetCart()
        {
            try
            {
                var count = 0;
                if (_Customer == null)
                {
                    var list = GetCookieCartByStoreCode();
                    if (list == null)
                    {
                        return count;
                    }
                    for (int i = 0; i < list.Count; i++)
                    {
                        count += list[i].Quantity;
                    }
                }
                else
                {
                    string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                    var list = _CartService.GetListProductByStoreCode(_Customer.Id, Path[1]);
                    for (int i = 0; i < list.Count; i++)
                    {
                        count += (int)list[i].Quantity;
                    }
                    RemoveCookie("Cookie.Cart");
                }
                return count;
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                throw ex;
            }
        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (_Customer == null)
                {
                    DeleteCart(Id);
                }
                else
                {
                    error = _CartService.DeleteProduct(_Customer.Id, Id);
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        [HttpPost]
        public IActionResult SetQuantityCart(int ProductId, int Quantity, int Limited, int LivestreamId)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (_Customer == null)
                {
                    string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                    SetCookieCart(ProductId, Quantity, Limited, LivestreamId , Path[1]);
                }
                else
                {
                    error = _CartService.SetQuantityProduct(_Customer.Id, LivestreamId, ProductId, Quantity);
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Controllers/LocationAddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Services.Geos;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class LocationAddressController : BaseController
    {
        private ILocationAddressService _location;
        private IAddressService _address;
        public LocationAddressController(ILocationAddressService location, IAddressService address)
        {
            _location = location;
            _address = address;
        }

        [HttpPost]
        public ActionResult GetListDistrictByStateProvinceId(string StateProvinceId)
        {
            try
            {
                return Json(_location.GetDistrictById(StateProvinceId));
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(ex);
            }
        }

        [HttpPost]
        public ActionResult GetListWardByDistrictId(string DistrictId)
        {
            try
            {
                return Json(_location.GetWardById(DistrictId));
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(ex);
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Data.DBContext.Models;
using LiveStreamStore.Lib.Models;
using LiveStreamStore.Lib.Services.Cart;
using LiveStreamStore.Lib.Services.Livestreams;
using LiveStreamStore.Lib.Services.Logs;
using LiveStreamStore.Lib.Services.Orders;
using LiveStreamStore.Lib.Services.Products;
using LiveStreamStore.Web.Frontend.Filters;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class OrderController : BaseController
    {
        private readonly ILivestreamService _LiveStreamService;
        private readonly IOrderService _OrderService;
        private readonly ICartService _CartService;
        private readonly IProductService _ProductService;
        private readonly ILogService _LogService;

        public OrderController(ILivestreamService liveStreamService, IOrderService orderService, ICartService cartService, IProductService productService, ILogService logService)
        {
            _LiveStreamService = liveStreamService;
            _OrderService = orderService;
            _CartService = cartService;
            _ProductService = productService;
            _LogService = logService;
        }

        [AuthFilter]
        public IActionResult History()
        {
             var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (_Customer == null)
                {
                    return RedirectToAction("Error404", "Customer");
                }
                return View(_OrderService.GetOrderTempByCustomer(_Customer.Id, 0));
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        [HttpPost]
        public PartialViewResult PartialListOrderHistory(int pageNumber)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var orderTemps = _OrderService.GetOrderTempByCustomer(_Customer.Id, pageNumber);
                ViewBag.CurrentTimeZoneOffSet = _Timezoneoffset;
                return PartialView("_PartialListOrderHistory", orderTemps);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public PartialViewResult PartialMobileListOrderHistory(int pageNumber)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var orderTemps = _OrderService.GetOrderTempByCustomer(_Customer.Id, pageNumber);
                return PartialView("_PartialMobileListOrderHistory", orderTemps);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public IActionResult CreateOrder(List<OrderDetail> createOrderItem, List<OrderTemp> createOrderTemp)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (createOrderItem.Any())
                {
                    for (int i = 0; i < createOrderItem.Count; i++)
                    {
                        var check = _CartService.CheckCartOrder(_Customer.Id, (int)createOrderItem[i].ProductId, (int)createOrderItem[i].Quantity);
                        if (check.Code != error.Code)
                        {
                            var product = _ProductService.GetProductById((int)createOrderItem[i].ProductId);
                            return Json(new { check, product.ProductInfo.Name });
                        }
                    }
                    for (int i = 0; i < createOrderItem.Count; i++)
                    {
                        var product = _ProductService.GetProductById((int)createOrderItem[i].ProductId);
                        createOrderItem[i].Price = product.Price;
                        error = _OrderService.CreateOrderDetail(createOrderItem[i]);
                        _OrderService.AddQuantityToProduct(createOrderItem[i].ProductId, createOrderItem[i].Quantity);
                        _CartService.AddQuantityToCart(_Customer.Id, createOrderItem[i].ProductId, createOrderItem[i].Quantity);
                        if (error.Code == Error.SUCCESS.Code)
                        {
                            createOrderTemp[i].OrderDetailId = error.GetData<OrderDetail>().Id;
                            error = _OrderService.CreateOrderTemp(createOrderTemp[i]);
                        }
                    }
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
            finally
            {
                var method = MethodBase.GetCurrentMethod();
                _Log.Info(_LogService.WriteLogFrontend(method, createOrderItem, createOrderTemp));
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Views/Cart/Index.cshtml
@model LiveStreamStore.Lib.Data.DBContext.Models.Customer
@{
    ViewData["Title"] = "Giỏ hàng";
    var listCart = ViewBag.CookieCart;
    var address = ViewBag.Address;
}

<div>
    <h3 class="shoppingCard" style="font-family: 'Font Awesome 5 Free';">
        GIỎ HÀNG (<span id="quantityProduct"></span> sản phẩm)
    </h3>
</div>

@if (listCart == null || listCart.Count == 0)
{
    <div class="card">
        <div class="card-body">
            <center>
                <img src="~/images/defaults/mascot@2x.png" alt="" height="160px" width="190px">
                <p>Không có sản phẩm nào trong giỏ hàng của bạn.</p>
                <a asp-controller="Livestream" asp-action="Index"><button type="button" class="btn waves-effect waves-light btn-warning">Tiếp tục mua sắm</button></a>
            </center>
        </div>
    </div>
}
else
{
    <div class="row" id="divCart">

        <div class="col-md-8" id="cartProduct">
            <div id="content">

            </div>
        </div>

        <div class="col-md-4">
            <div class="card" id="styleCart">
                <div class="card-body">
                    @if (Model != null)
                    {
                        <div class="card-header">
                            <h4>Thông tin và địa chỉ nhận hàng</h4>
                            <div>
                                <i class="fa fa-phone" aria-hidden="true"></i>&nbsp;<span id="phone">@Model.Phone</span>
                            </div>
                            <div>
                                <i class="fas fa-envelope"></i>&nbsp;<span id="email">@Model.Email</span>
                            </div>
                            <div class="address">
                                @if (address == null)
                                {
                                    <i class="fas fa-map-marker-alt">
                                        &nbsp;<span class="addressName"></span>
                                        <span>
                                            <a id="addAddress" data-toggle="modal" data-target="#add-address" style="color: #5581d4; cursor: pointer;">Thêm địa chỉ</a>
                                        </span>
                                    </i>
                                }
                                else
                                {
                                    <i class="fas fa-map-marker-alt">&nbsp; *, @address.WardName , @address.DistrictName , @address.StateProvinceName</i>
                                    @*<div>
                                        <a id="editAddress" data-toggle="modal" data-target="#add-address" style="color: #5581d4; cursor: pointer;">Sửa địa chỉ</a>
                                    </div>*@
                                    <div class="addressName" hidden>@address.Address1</div>
                                    <input class="AddressId" value="@address.Id" hidden />
                                    <input class="WardId" value="@address.WardId" hidden />
                                    <input class="DistrictId" value="@address.DistrictId" hidden />
                                    <input class="StateProvinceId" value="@address.StateProvinceId" hidden />
                                }
                            </div>
                        </div>
                    }

                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div id="calendar-events" class="mt-3">
                                <div class="tamTinh">Tạm tính: <span class="totalPrice" style="float: right;">0</span></div>
                                <hr class="solid">
                                <div>
                                    <h4 class="thanhTien">Thành tiền: <span class="totalOrder" style="float: right; color: red;">0</span></h4>
                                </div>
                            </div>
                            <br />
                            <a id="clickOrder" style="color: white;" class="btn btn-danger btn-block waves-effect waves-light">
                                <i class="ti-plus"></i> Đặt hàng
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

    @Html.Partial("_PartialModalAddress")

}
@*<script src="~/js/AjaxLoading.js"></script>*@

<script>

    //Khi click tao dia chi
    $('#addAddress').click(function () {
        $("#myModalLabel").text("Thêm địa chỉ");
        $("#Id").val(0);
        CreateAddress();
    });

    //Khi click chinh sua dia chi
    $('#editAddress').click(function () {
        $("#myModalLabel").text("Chỉnh sửa địa chỉ");

        var addressId = $('.AddressId').val();
        var name = $('.addressName').text();
        $("#Id").val(addressId);
        $('#addressName').val(name);

        var state = $('.StateProvinceId').val();
        var district = $('.DistrictId').val();
        var ward = $('.WardId').val();
        EditAddress(state, district, ward)
    });

    function getListCart() {
        $.ajax({
            type: "POST",
            url: "@Url.Action("GetListCart", "Cart")",
            dataType: "html",
            success: function (result) {
                $("#content").html(result);
            }
        });
    }
    $(document).ready(getListCart());

    //Xoa san pham
    $('#divCart').on('click', '#delete', function () {
        var current = $(this).closest("#clickCart");
        var id = current.find('.id').text();
        $.ajax({
            type: "POST",
            url: "@Url.Action("Delete", "Cart")",
            data: {
                Id: id
            },
            success: function (response) {
                if (response.code == error.success.Code) {
                    getListCart();
                    getCookie();
                    if ($('div[id="clickCart"]').length == 1) {
                        window.location.reload();
                    }
                }
                else {
                    toastr.success("Thất bại");
                }
            }
        });
    });

    //Tao hoac sua dia chi
    $('#btnAddress').click(function () {
        var required = $("#formAddress").find($("input[required]"));
        var checkRequired = required.length;
        required.each(function () {
            if ($(this).val() == "") {
                $(this).css('border-color', 'red');
                $("#AddressError").html(`<label>Vui lòng không được để trống trường báo đỏ.</label>`).show();
            } else {
                $(this).css('border-color', 'LightGray');
                checkRequired = checkRequired - 1;
            }
        });

        if (checkRequired == 0) {
            var id = $("#Id").val();
            var idCus = $('.idCus').val();
            var address = $('#addressName').val();
            var state = $("#StateProvinceId").val();
            var stateName = $('#StateProvinceId :selected').text();
            var district = $("#DistrictId").val();
            var districtName = $('#DistrictId :selected').text();
            var ward = $("#WardId").val();
            var wardName = $('#WardId :selected').text();
            $.ajax({
                type: "POST",
                url: "@Url.Action("CreateOrUpdate", "Address")",
                data: {
                    address: {
                        Id: id,
                        CustomerId: idCus,
                        StateProvinceId: state,
                        DistrictId: district,
                        WardId: ward,
                        StateProvinceName: stateName,
                        DistrictName: districtName,
                        WardName: wardName,
                        Address1: address
                    }
                },
                success: function (data) {
                    if (data.code == error.success.Code) {
                        if (id == 0) {
                            toastr.success("Tạo địa chỉ thành công");
                        } else {
                            toastr.success("Chỉnh sửa địa chỉ thành công");
                        }
                        $("#add-address").modal("hide");
                        setTimeout(function () {
                            window.location.reload();
                        }, 1000);
                    }
                }
            });
        }
    });

    //Button dat hang
    $('#clickOrder').click(function () {

        document.getElementById('loginform').reset();
        $('#LoginError').hide();
        var idCustomer = $('.idCus').val();
        var nameAddress = $('.addressName').text();
        if (idCustomer == 0) {
            $('#modalLogin').modal('show');
        }
        else if (nameAddress == "") {
            $('#addAddress').click();
        }
        else {
            var listDetails = [], listTemp = [];
            var Details, Temp;

            let arr = $('div[id="clickCart"]');
            for (var i = 0; i < arr.length; i++) {
                var current = $(arr[i]);

                //Them vao list order details
                var idProduct = current.find('.id').text();
                var quantity = current.find('#number').val();
                Details = { ProductId: idProduct, Quantity: quantity }
                listDetails.push(Details);

                //Them vao list order temp
                var livestreamId = current.find('.idLivestream').val();
                Temp = { CustomerId: idCustomer, LiveStreamId: livestreamId, IsPreSale: "True" }
                listTemp.push(Temp);
            }
            $.ajax({
               beforeSend: function () {
                    $(".preloader").css("background", "#fff6");
                    $('.preloader').show();
               },
                complete: function () {
                    $('.preloader').hide();
                    $(".preloader").css("background", "##fff");
                },
                type: "POST",
                url: "@Url.Action("CreateOrder", "Order")",
                data: {
                    createOrderItem: listDetails,
                    createOrderTemp: listTemp
                },
                success: function (data) {
                    var nameCode = Object.values(data)[1];
                    var checkCode = Object.values(data)[0];
                    if (checkCode.code == error.check_product.Code) {
                        toastr.warning("Món hàng " + nameCode + " không đủ số lượng");
                    } else if (checkCode.code == error.limited.Code) {
                        toastr.warning("Món hàng " + nameCode + " vượt quá số lượng được mua");
                    }
                    else if (data.code == error.success.Code) {
                        var pathname = window.location.pathname;
                        $('#clickOrder').hide();
                        setTimeout(function () {
                            window.location.href = pathname.slice(0, 4) + "/Livestream/Index";
                        }, 3000);
                        swal({
                            title: "Đơn hàng của bạn đã được thêm",
                            text: "Vui lòng đợi liên hệ từ shop",
                            icon: "success",
                            showCancelButton: false,
                            dangerMode: true
                        }).then((will) => {
                            if (will) {
                                window.location.href = pathname.slice(0, 4) + "/Livestream/Index";
                            }
                        })
                    }
                }
            })
        }
    });

    $(document).ready(function () {
        var required = document.querySelectorAll("input[required]");
        required.forEach(function (element) {
            $("input[type='text']").change(function () {
                if (element.value.trim() == "") {
                    element.style["border"] = "1px solid red";
                } else {
                    element.style["border"] = "1px solid LightGray";
                }
            });
        });
    })

</script>