LiveStreamStore.Web.Frontend/Controllers/LivestreamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Models;
using LiveStreamStore.Lib.Models.SearchFilter;
using LiveStreamStore.Lib.Services.Cart;
using LiveStreamStore.Lib.Services.Livestreams;
using LiveStreamStore.Lib.Services.Products;
using LiveStreamStore.Lib.Services.Users;
using LiveStreamStore.Web.Frontend.Filters;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class LivestreamController : BaseController
    {
        private readonly ILivestreamService _LiveStreamService;
        private readonly IProductService _ProductService;
        private readonly IUserService _UserStoreService;
        private readonly ICartService _CartService;

        public LivestreamController(ILivestreamService liveStreamService, IProductService productService, IUserService userStoreService, ICartService cartService)
        {
            _LiveStreamService = liveStreamService;
            _ProductService = productService;
            _UserStoreService = userStoreService;
            _CartService = cartService;
        }

        [AuthFilter]
        public IActionResult Index(string StoreCode)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var check = _UserStoreService.GetUserStoreByStoreCode(StoreCode);
                if (check != null)
                {
                    ViewBag.StoreName = check.Store.Name;
                    return View();
                }
                return RedirectToAction("Error404", "Customer");
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        [HttpPost]
        public PartialViewResult GetListByStreaming(string timezoneoffset)
        {
            try
            {
                if (_Timezoneoffset == null)
                {
                    SetSessionTimeZone(timezoneoffset);
                }
                ViewBag.CurrentTimeZoneOffSet = _Timezoneoffset;
                string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                var livestreams = _LiveStreamService.GetLiveStreamByStreaming(Path[1]);
                return PartialView("_PartialListLiveStream", livestreams);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public PartialViewResult GetProductBeforeLiveStream(int idLivestream, int pageNumber)
        {
            try
            {
                ViewBag.Customer = _Customer;
                if (_Customer != null)
                {
                    string[] Path = (HttpContext.Request.Path).ToString().Split('/');
                    ViewBag.ListCart = _CartService.GetAllListProductByStoreCode(_Customer.Id, Path[1]);
                }
                var products = _ProductService.GetListProductByPage(idLivestream, pageNumber);
                return PartialView("_PartialProductBeforeLiveStream", products);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }
        
        [AuthFilter]
        public IActionResult Products(int id)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                return View(_LiveStreamService.GetLiveStreamById(id));
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LiveStream.Web.Frontend.Controllers;
using LiveStreamStore.Lib.Data.DBContext.Models;
using LiveStreamStore.Lib.Models;
using LiveStreamStore.Lib.Services.Cart;
using LiveStreamStore.Lib.Services.Livestreams;
using LiveStreamStore.Lib.Services.Logs;
using LiveStreamStore.Lib.Services.Orders;
using LiveStreamStore.Lib.Services.Products;
using LiveStreamStore.Web.Frontend.Filters;

namespace LiveStreamStore.Web.Frontend.Controllers
{
    public class OrderController : BaseController
    {
        private readonly ILivestreamService _LiveStreamService;
        private readonly IOrderService _OrderService;
        private readonly ICartService _CartService;
        private readonly IProductService _ProductService;
        private readonly ILogService _LogService;

        public OrderController(ILivestreamService liveStreamService, IOrderService orderService, ICartService cartService, IProductService productService, ILogService logService)
        {
            _LiveStreamService = liveStreamService;
            _OrderService = orderService;
            _CartService = cartService;
            _ProductService = productService;
            _LogService = logService;
        }

        [AuthFilter]
        public IActionResult History()
        {
             var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (_Customer == null)
                {
                    return RedirectToAction("Error404", "Customer");
                }
                return View(_OrderService.GetOrderTempByCustomer(_Customer.Id, 0));
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
        }

        [HttpPost]
        public PartialViewResult PartialListOrderHistory(int pageNumber)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var orderTemps = _OrderService.GetOrderTempByCustomer(_Customer.Id, pageNumber);
                ViewBag.CurrentTimeZoneOffSet = _Timezoneoffset;
                return PartialView("_PartialListOrderHistory", orderTemps);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public PartialViewResult PartialMobileListOrderHistory(int pageNumber)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                var orderTemps = _OrderService.GetOrderTempByCustomer(_Customer.Id, pageNumber);
                return PartialView("_PartialMobileListOrderHistory", orderTemps);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return PartialView("_PartialError", ex);
            }
        }

        [HttpPost]
        public IActionResult CreateOrder(List<OrderDetail> createOrderItem, List<OrderTemp> createOrderTemp)
        {
            var error = new ErrorObject(Error.SUCCESS);
            try
            {
                if (createOrderItem.Any())
                {
                    for (int i = 0; i < createOrderItem.Count; i++)
                    {
                        var check = _CartService.CheckCartOrder(_Customer.Id, (int)createOrderItem[i].ProductId, (int)createOrderItem[i].Quantity);
                        if (check.Code != error.Code)
                        {
                            var product = _ProductService.GetProductById((int)createOrderItem[i].ProductId);
                            return Json(new { check, product.ProductInfo.Name });
                        }
                    }
                    for (int i = 0; i < createOrderItem.Count; i++)
                    {
                        var product = _ProductService.GetProductById((int)createOrderItem[i].ProductId);
                        createOrderItem[i].Price = product.Price;
                        error = _OrderService.CreateOrderDetail(createOrderItem[i]);
                        _OrderService.AddQuantityToProduct(createOrderItem[i].ProductId, createOrderItem[i].Quantity);
                        _CartService.AddQuantityToCart(_Customer.Id, createOrderItem[i].ProductId, createOrderItem[i].Quantity);
                        if (error.Code == Error.SUCCESS.Code)
                        {
                            createOrderTemp[i].OrderDetailId = error.GetData<OrderDetail>().Id;
                            error = _OrderService.CreateOrderTemp(createOrderTemp[i]);
                        }
                    }
                }
                return Json(error);
            }
            catch (Exception ex)
            {
                _Log.Error(ex);
                return Json(error.System(ex));
            }
            finally
            {
                var method = MethodBase.GetCurrentMethod();
                _Log.Info(_LogService.WriteLogFrontend(method, createOrderItem, createOrderTemp));
            }
        }
    }
}

LiveStreamStore.Web.Frontend/Views/Order/History.cshtml
@model List<LiveStreamStore.Lib.Data.DBContext.Models.OrderTemp>
@{
    ViewData["Title"] = "Đơn hàng";
}

<style>
    #mobile {
        display: none;
    }
    /* ipad mini */
    @@media only screen and (min-device-width: 320px) and (max-device-width: 768px) and (-webkit-min-device-pixel-ratio: 1) {
        .table-responsive {
            display: none;
        }

        #mobile {
            display: block;
        }
    }
</style>

<div class="row" id="foot">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title" style="font-family: 'Font Awesome 5 Free';">Đơn hàng của tôi</h2>

                @if (Model.Any())
                {
                    <div class="table-responsive">
                        <table id="demo-foo-addrow" class="table table-hover no-wrap">
                            <thead>
                                <tr class="footable-header">
                                    <th>Sản Phẩm</th>
                                    <th>Ngày Mua</th>
                                    <th>Số Lượng</th>
                                    <th>Tổng Tiền</th>
                                    @*<th>Trạng Thái Đơn Hàng</th>*@
                                </tr>
                            </thead>
                            <tbody>
                                
                            </tbody>
                        </table>
                    </div>
                    <div id="mobile">

                    </div>
                }
                else
                {
                    <center>
                        <p>Bạn chưa có đơn hàng nào.</p>
                        <a asp-controller="Livestream" asp-action="Index"><button type="button" class="btn waves-effect waves-light btn-warning">Tiếp tục mua sắm</button></a>
                    </center>
                }

            </div>
        </div>
    </div>
</div>

<script>
    // LazyLoading Order
    var ajaxCallUrl, page = 0, inCallback = false, append;

    if ($('#mobile').css('display') == 'none') {
        ajaxCallUrl = '@Url.Action("PartialListOrderHistory", "Order")';
        append = $("tbody");
    } else {
        ajaxCallUrl = '@Url.Action("PartialMobileListOrderHistory", "Order")';
        append = $("#mobile");
    }

    // function getListByFilter
    function getListByFilter() {
        $.ajax({
            url: ajaxCallUrl,
            type: "POST",
            dataType: "html",
            success: (function (result) {
                append.html(result);
            })
        })
    }
    // Run Page Index Auto Load Funtion getListByFilter
    $(document).ready(getListByFilter);

    $(document).on('scroll', onScroll);

    function onScroll() {
        if (Math.ceil($(window).scrollTop()) + $(window).height() == $(document).height()) {
            if (page > -1 && !inCallback) {
                inCallback = true;
                page++;
                $.ajax({
                    type: 'POST',
                    url: ajaxCallUrl,
                    data: {
                        pageNumber: page
                    },
                    success: function (data, textstatus) {
                        if (data != '') {
                            append.append(data);
                        }
                        else {
                            page = -1;
                        }

                        inCallback = false;
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert(errorThrown);
                    }
                });
            }
        }
    }
</script>

LiveStreamStore.Web.Frontend/Views/Order/_PartialListOrderHistory.cshtml
@model List<LiveStreamStore.Lib.Data.DBContext.Models.OrderTemp>
@{
    var TimeZone = int.Parse(ViewBag.CurrentTimeZoneOffSet);
}
@foreach (var item in Model)
{
    var localTimeCreateDate = item.CreatedDateUtc?.AddSeconds(TimeZone);

    <tr class="tr-list-livestream">
        @if (item.OrderDetail.Product.ProductInfo.Image != null)
        {
            <td><img src="@(item.OrderDetail.Product.ProductInfo.Image.Domain + item.OrderDetail.Product.ProductInfo.Image.FileUrl) " height="50" width="50" /> @item.OrderDetail.Product.ProductInfo.Name</td>
        }
        else
        {
            <td><img src="~/images/defaults/ProductDefault.png" height="50" width="50" /> @item.OrderDetail.Product.ProductInfo.Name</td>
        }
        <td>@localTimeCreateDate.Day/@localTimeCreateDate.Month/@localTimeCreateDate.Year</td>
        <td>@item.OrderDetail.Quantity</td>
        <td class="totalPrice">@item.OrderDetail.TotalPrice</td>
    </tr>
}

<script>
    var totalPrice = document.getElementsByClassName('totalPrice');
    for (var i = 0; i < totalPrice.length; i++) {
        if (totalPrice[i].innerHTML.indexOf('đ') === -1) {
            totalPrice[i].innerHTML = Intl.NumberFormat().format(totalPrice[i].innerHTML) + " đ";
        }
    }
</script>

LiveStreamStore.Web.Frontend/Views/Order/_PartialMobileListOrderHistory.cshtml
@model List<LiveStreamStore.Lib.Data.DBContext.Models.OrderTemp>

@foreach (var item in Model)
{
    var localTimeCreateDate = new DateTimeOffset((DateTime)item.CreatedDateUtc, TimeSpan.FromHours(0)).ToLocalTime().DateTime;
    <div>
        <span style="font-weight: bold; font-size: larger">@item.OrderDetail.Product.ProductInfo.Name</span>
        <br>Ngày đặt hàng: @localTimeCreateDate.Day/@localTimeCreateDate.Month/@localTimeCreateDate.Year
        <br>Số lượng: @item.OrderDetail.Quantity
        <br>Tổng tiền: <span class="totalPrice">@item.OrderDetail.TotalPrice</span>
    </div>
    <hr />
}

<script>
    var totalPrice = document.getElementsByClassName('totalPrice');
    for (var i = 0; i < totalPrice.length; i++) {
        if (totalPrice[i].innerHTML.indexOf('đ') === -1) {
            totalPrice[i].innerHTML = Intl.NumberFormat().format(totalPrice[i].innerHTML) + " đ";
        }
    }
</script>